In [5]:
import numpy as np
import scipy.linalg as la

In [29]:
def diagonalize(A):
    eigenvalues, eigenvectors = la.eig(A)
    
    return(np.diag(eigenvalues), np.matrix(eigenvectors))

Z = np.matrix([[1j,0,-1j],
              [0,1,-1-4j],
              [2-1j,1j,3]])

# calculate A#conj(A), where A = Z^HZ
A = Z.getH() * Z
A_Aconj = A * la.sqrtm(la.inv(A) * np.conj(A))

# find S such that A#conj(A) = e^{2S}
# since A#conj(A) is orthogonally diagonalizable, then A#conj(A) = PDP'
# so, we get S = 1/2 * log(PDP')
D, P = diagonalize(A_Aconj)
S = np.real(1/2 * P * la.logm(D) * P.getT())

# calculate Y = e^{-S}Ae^{-S} dan find K such that Y = e^{iK}
# since Y is unitarilly diagonalizable, then Y = UDU*
# so, we get iK = log(UDU*)
Y = la.expm(-S) * A * la.expm(-S)
K1 = np.angle(Y)
D, U = diagonalize(Y)
K2 = np.imag(U * la.logm(D) * U.getH())
print(K1)
print(K2)

[[ 4.69042325e-17  1.69637796e+00  1.89121496e-01]
 [-1.69637796e+00  5.63748213e-17 -1.52938687e+00]
 [-1.89121496e-01  1.52938687e+00  2.95826891e-17]]
[[ 1.20130503e-15  1.71227759e+00  2.66173091e-01]
 [-1.71227759e+00  8.90403880e-16 -2.98888382e+00]
 [-2.66173091e-01  2.98888382e+00  9.92075543e-16]]


In [19]:
Z = np.matrix([[0,1.7113j,0.267j],
               [-1.7113j,0,-2.988j],
               [-0.267j,2.988j,0]])
np.imag(Z)

matrix([[ 0.    ,  1.7113,  0.267 ],
        [-1.7113,  0.    , -2.988 ],
        [-0.267 ,  2.988 ,  0.    ]])

In [ ]:
def diagonalize(A):
    eigenvalues, eigenvectors = la.eig(A)
    
    return(np.diag(eigenvalues), np.matrix(eigenvectors))

def bipolar(Z):
    # check if Z is nonsingular matrix
    if abs(la.det(Z)) < 1e-5:
        raise NameError("The matrix is singular. Can't use bipolar decomposition.")

    # calculate A#conj(A), where A = Z^HZ
    A = Z.getH() * Z
    A_Aconj = A * la.sqrtm(la.inv(A) * np.conj(A))
    
    # find S such that A#conj(A) = e^{2S}
    # since A#conj(A) is orthogonally diagonalizable, then A#conj(A) = PDP'
    # so, we get S = 1/2 * log(PDP')
    D, P = diagonalize(A_Aconj)
    S = np.real(1/2 * P * la.logm(D) * P.getT())
    
    # calculate Y = e^{-S}Ae^{-S} dan find K such that Y = e^{iK}
    # since Y is unitarilly diagonalizable, then Y = UDU*
    # so, we get iK = log(UDU*)
    Y = la.expm(-S) * A * la.expm(-S)
    K = np.angle(Y)
    # D, U = diagonalize(Y)
    # K = np.imag(U * la.logm(D) * U.getH())

    # calculate W
    K = 1/2 * K
    W = Z * la.expm(-S) * la.expm(-1j * K)
    
    # calculate W'W dan find T such that W'W = e^{2iT}
    # since W'W is unitarilly diagonalizable, then W'W = UDU*
    # so, we get iT = 1/2 * log(UDU*)
    Wtrans_W = W.getT() * W
    D, U = diagonalize(Wtrans_W)
    Q4=matrix(Q4)
    newD4=diag(angle(D4))
    M=Q4*newD4*Q4.getH()
    C1=0.5*M