Hi! This page will show you some examples on how to use the Bipolar Decomposition. You don't need to install the library using `pip` or anything since it's not registered on pypi, but make sure the `bipolar_decomposition.py` file is in the same folder with the code you want to call. Well..you can say that this is a local library.

Okay, so let's get started!

First, let's import some libraries we need.

In [1]:
import numpy as np
import scipy.linalg as la
import bipolar_decomposition as bd

Basically, we only need two libraries, `numpy` and of course `bipolar_decomposition`. `numpy` is used to create the matrix you want to decompose, while `bipolar_decomposition` to decompose your matrix of course. `scipy.linalg` is used to exponentiate the matrix to check our results. Since the Bipolar Decomposition might be used under other program, "maybe" `scipy.linalg` will be needed.

Next, let's create a sample matrix.

In [2]:
Z = np.matrix([[1j,0,-1j],
               [0,1,-1-4j],
               [2-1j,1j,3]])

`bipolar_decomposition` uses `numpy.matrix` as its main data structure. It's because we can multiply the matrices by using the usual multiplication operators (\*) rather than matrix multiplication operators in `numpy.array` (@) which is not so familiar to read. Also, we can do conjugate transpose easily using `numpy.matrix`.

Next, let's decompose our matrix.

In [3]:
L,T,K,S = bd.bipolar(Z)

In [4]:
L

matrix([[ 7.24223580e-12, -6.87599579e-01, -6.51877438e-01],
        [ 6.87599579e-01,  7.74021480e-12, -5.56829653e-01],
        [ 6.51877438e-01,  5.56829653e-01,  7.43515883e-12]])

In [5]:
T

matrix([[ 0.26200499, -0.12762701, -0.71432666],
        [-0.12762701,  0.35504189,  0.42484587],
        [-0.71432666,  0.42484587,  0.95374945]])

In [6]:
K

matrix([[ 3.41221334e-12,  8.56138793e-01,  1.33086546e-01],
        [-8.56138793e-01, -1.58962279e-11, -1.49444191e+00],
        [-1.33086545e-01,  1.49444191e+00,  1.24904225e-11]])

In [7]:
S

matrix([[ 0.52417654, -0.01319968, -0.33864507],
        [-0.01319968, -1.04365904, -0.07979849],
        [-0.33864507, -0.07979849,  0.5194825 ]])

It's easy right? If you want to check whether the result is correct, let's multiply them.

In [8]:
la.expm(L) @ la.expm(1j * T) @ la.expm(1j * K) @ la.expm(S)

array([[ 5.24254686e-12+1.00000000e+00j, -5.24165856e-12+4.33356476e-12j,
         1.73343347e-11-1.00000000e+00j],
       [ 7.86709586e-12+7.06612546e-12j,  1.00000000e+00+9.71445147e-16j,
        -1.00000000e+00-4.00000000e+00j],
       [ 2.00000000e+00-1.00000000e+00j, -1.22124533e-15+1.00000000e+00j,
         3.00000000e+00+3.53969631e-12j]])

Wait! I know what you're thinking. In the end, we use (@) operators to multiply those matrices. Well..it's too bad that `scipy.linalg.expm` will give a `numpy.array` as the output. So, we don't have any choice but to use (@).

Well..I think that's all on how to use the `bipolar_decomposition`. To make you certain, I will give you another example since there are two cases where $\det{Q}=-1$ (if you have read the paper).

In [9]:
Z = np.matrix([[2019j,3,2+1j],
               [1708+1j,2839,0],
               [1910+1j,1j,0]])

In [10]:
L,T,K,S = bd.bipolar(Z)

In [11]:
L

matrix([[-1.67322258e-12, -4.91208821e-02, -2.90200863e+00],
        [ 4.91208821e-02, -1.40041070e-13,  4.63268036e-01],
        [ 2.90200863e+00, -4.63268036e-01,  1.87648392e-12]])

In [12]:
T

matrix([[ 1.68552843, -0.55020943,  1.90239293],
        [-0.55020943,  0.17960386, -0.62208703],
        [ 1.90239293, -0.62208703,  1.74031655]])

In [13]:
K

matrix([[-2.86043271e-14, -4.90970726e-04, -4.00279654e-01],
        [ 4.90970727e-04, -2.67847438e-14,  1.31401332e-01],
        [ 4.00279654e-01, -1.31401332e-01,  5.53114191e-14]])

In [14]:
S

matrix([[ 7.87691637e+00,  3.34883039e-01,  1.84898399e-03],
        [ 3.34883039e-01,  7.84447525e+00, -1.04795075e-03],
        [ 1.84898399e-03, -1.04795075e-03,  5.89393224e-01]])

In [15]:
la.expm(L) @ la.expm(1j * T) @ la.expm(1j * K) @ la.expm(S)

array([[2.80575563e-12+2.01900000e+03j, 3.00000000e+00+1.25631769e-10j,
        2.00000000e+00+1.00000000e+00j],
       [1.70800000e+03+1.00000000e+00j, 2.83900000e+03-1.14954263e-14j,
        4.37319451e-14-8.98349320e-14j],
       [1.91000000e+03+1.00000000e+00j, 2.69027856e-13+1.00000000e+00j,
        9.95870053e-14-2.04770649e-13j]])

Based on the paper, you can decompose any size of complex matrix (as long as it's a square matrix).

In [16]:
Z = np.matrix([[2019j,3,2+1j,1708+1j],
               [2839,0,1910+1j,1j],
               [0,1890j,0,919],
               [3+3j,21+12j,2018,0]])

In [17]:
L,T,K,S = bd.bipolar(Z)

In [18]:
L

matrix([[ 1.22124533e-15, -5.75450896e-01, -8.61101446e-01,
          1.44521372e+00],
        [ 5.75450896e-01, -5.82867088e-16,  1.35484227e+00,
         -5.90443650e-01],
        [ 8.61101446e-01, -1.35484227e+00,  6.52256027e-16,
         -7.48745057e-01],
        [-1.44521372e+00,  5.90443650e-01,  7.48745057e-01,
          6.10622664e-15]])

In [19]:
T

matrix([[-4.70983074e-02,  2.62306346e-01,  1.28849066e-02,
          3.67703740e-01],
        [ 2.62306346e-01, -1.52251449e+00, -6.29733349e-02,
          6.98792361e-02],
        [ 1.28849066e-02, -6.29733349e-02, -3.56863262e-03,
         -1.37348256e-01],
        [ 3.67703740e-01,  6.98792361e-02, -1.37348256e-01,
          5.08071651e-04]])

In [20]:
K

matrix([[-3.73972999e-18, -1.47634099e-03, -6.74107277e-04,
         -3.80360502e-01],
        [ 1.47634099e-03,  4.46420245e-17, -3.27299104e-03,
         -3.24918335e-01],
        [ 6.74107277e-04,  3.27299104e-03, -4.26091454e-17,
          1.48119983e-01],
        [ 3.80360502e-01,  3.24918335e-01, -1.48119983e-01,
          3.40652663e-18]])

In [21]:
S

matrix([[ 7.95422850e+00, -1.02820274e-01,  3.59702571e-01,
          4.04541626e-04],
        [-1.02820274e-01,  7.45504013e+00,  4.76605986e-02,
         -1.99226342e-04],
        [ 3.59702571e-01,  4.76605986e-02,  7.79801698e+00,
         -8.32437939e-04],
        [ 4.04541626e-04, -1.99226342e-04, -8.32437939e-04,
          7.33658702e+00]])

In [22]:
la.expm(L) @ la.expm(1j * T) @ la.expm(1j * K) @ la.expm(S)

array([[ 2.10609308e-13+2.01900000e+03j,  3.00000000e+00-1.54573004e-12j,
         2.00000000e+00+1.00000000e+00j,  1.70800000e+03+1.00000000e+00j],
       [ 2.83900000e+03-4.26375894e-13j, -4.53580610e-12+3.16186270e-12j,
         1.91000000e+03+1.00000000e+00j,  1.19720900e-12+1.00000000e+00j],
       [-1.92235117e-12-3.35103581e-12j,  4.40936176e-12+1.89000000e+03j,
        -3.98181488e-12-4.44610483e-12j,  9.19000000e+02-1.18299814e-12j],
       [ 3.00000000e+00+3.00000000e+00j,  2.10000000e+01+1.20000000e+01j,
         2.01800000e+03-2.42891691e-13j, -1.28275168e-12-3.87882955e-12j]])